POST http://localhost:8080/user
Content-Type: application/json

{
  "kullanici_adi": "atakan_dev",
  "email": "atakan@mail.com",
  "sifre": "atakan12"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "kullanici_adi": "atakan_dev",
  "password": "atakan12"
}

###

GET http://localhost:8080/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjkyMDI2MTIsInVzZXJfaWQiOjN9.W5Pbml35psDRAvjtcEQk-QkhDsQtLT-fkK9uqTnrMVQ
Content-Type: application/json